apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: my-webapp
        image: my-dockerhub-acct/my-webapp
        resources: #per pod
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000